---

- hosts: all
  tasks:

  - name: Update repository index
    ansible.builtin.dnf:
      update_cache: yes

  - name: install apache package
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: install apache and php packages
    package:
      name:
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
      state: latest

  - name: start and enable apache service
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes
