  - name: "Upgrade all installed packages using DNF module for Dnf hosts"
    ansible.builtin.dnf:
      name: "*"
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Update all packages to their latest version and the cache too in Ubuntu host
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
